package DSC;

import javax.swing.JFrame;

/**
 *
 * @author Aliens_Michael
 */
public class DSC_Main extends javax.swing.JFrame {

    /*
                Static variables for Condition Statements.
     */
    public static boolean getData = true;
    public static boolean checkGraph = true;

    /**
     * Creates new form DSC_Main
     */
    public DSC_Main() {
        DBClass.getInstance();
        initComponents();
        pnlBarChartActive.removeAll();
        pnlBarChartActive.repaint();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlHeading = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pnlTables = new javax.swing.JPanel();
        lblView = new javax.swing.JLabel();
        btnRouteView = new javax.swing.JButton();
        btnViewOrders = new javax.swing.JButton();
        btnChangeChart = new javax.swing.JButton();
        btnChangeStatistics = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        pnlReports = new javax.swing.JPanel();
        btnDriverRpt = new javax.swing.JButton();
        btnChefRpt = new javax.swing.JButton();
        btnPackerRpt = new javax.swing.JButton();
        btnHandlerRpt = new javax.swing.JButton();
        lblGenerate = new javax.swing.JLabel();
        pnlMainChartBackground = new javax.swing.JPanel();
        pnlBarChartActive = new javax.swing.JPanel();
        pnlPieChart = new javax.swing.JPanel();
        pnlBarChartInActive = new javax.swing.JPanel();
        pnlTextStats = new javax.swing.JPanel();
        pnlMealTypeStats = new javax.swing.JPanel();
        lblStandardMeal = new javax.swing.JLabel();
        lblLowCarb = new javax.swing.JLabel();
        lblKiddies = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblStandardTotal = new javax.swing.JLabel();
        lblLowCarbTotal = new javax.swing.JLabel();
        lblKiddiesTotal = new javax.swing.JLabel();
        lblStandardMeal1 = new javax.swing.JLabel();
        lblLowCarb1 = new javax.swing.JLabel();
        lblKiddies1 = new javax.swing.JLabel();
        lblStandardTotalInActive = new javax.swing.JLabel();
        lblLowCarbTotalInActive = new javax.swing.JLabel();
        lblKiddiesTotalinActive = new javax.swing.JLabel();
        lblActive = new javax.swing.JLabel();
        lblInActive = new javax.swing.JLabel();
        pnlFamilySizeStats = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lblSingleFamilySize = new javax.swing.JLabel();
        lblCoupleFamilySize = new javax.swing.JLabel();
        lblThreeFamilySize = new javax.swing.JLabel();
        lblFourFamilySize = new javax.swing.JLabel();
        lblFiveFamilySize = new javax.swing.JLabel();
        lblSixFamilySize = new javax.swing.JLabel();
        lblSingleFamilySizeTotal = new javax.swing.JLabel();
        lblCoupleFamilySizeTotal = new javax.swing.JLabel();
        lblThreeFamilySizeTotal = new javax.swing.JLabel();
        lblFourFamilySizeTotal = new javax.swing.JLabel();
        lblFiveFamilySizeTotal = new javax.swing.JLabel();
        lblSixFamilySizeTotal = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lblMoreThanSixFamilySize = new javax.swing.JLabel();
        lblMoreThanSixFamilySizeTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DSC");

        pnlBackground.setBackground(new java.awt.Color(0, 153, 0));

        pnlHeading.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/DSC.png"))); // NOI18N

        lblName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblName.setText("DOORSTEP CHEF");

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlTables.setBackground(new java.awt.Color(0, 204, 51));
        pnlTables.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblView.setText("View");

        btnRouteView.setText("Route View");
        btnRouteView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRouteViewActionPerformed(evt);
            }
        });

        btnViewOrders.setText("View Orders");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });

        btnChangeChart.setText("Change Chart");
        btnChangeChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeChartActionPerformed(evt);
            }
        });

        btnChangeStatistics.setText("Change Statistics");
        btnChangeStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStatisticsActionPerformed(evt);
            }
        });

        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTablesLayout = new javax.swing.GroupLayout(pnlTables);
        pnlTables.setLayout(pnlTablesLayout);
        pnlTablesLayout.setHorizontalGroup(
            pnlTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRouteView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlaceOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTablesLayout.createSequentialGroup()
                        .addGroup(pnlTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChangeChart, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChangeStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTablesLayout.setVerticalGroup(
            pnlTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblView, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRouteView, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangeChart, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangeStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlReports.setBackground(new java.awt.Color(0, 204, 51));
        pnlReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnDriverRpt.setText("Driver Report");
        btnDriverRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverRptActionPerformed(evt);
            }
        });

        btnChefRpt.setText("Chef Report");
        btnChefRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChefRptActionPerformed(evt);
            }
        });

        btnPackerRpt.setText("Packer Report");
        btnPackerRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackerRptActionPerformed(evt);
            }
        });

        btnHandlerRpt.setText("Handler Report");
        btnHandlerRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHandlerRptActionPerformed(evt);
            }
        });

        lblGenerate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGenerate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGenerate.setText("Generate Reports");

        javax.swing.GroupLayout pnlReportsLayout = new javax.swing.GroupLayout(pnlReports);
        pnlReports.setLayout(pnlReportsLayout);
        pnlReportsLayout.setHorizontalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDriverRpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChefRpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPackerRpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHandlerRpt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlReportsLayout.setVerticalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDriverRpt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChefRpt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPackerRpt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHandlerRpt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(684, Short.MAX_VALUE))
        );

        pnlMainChartBackground.setBackground(new java.awt.Color(0, 153, 0));

        pnlBarChartActive.setBackground(new java.awt.Color(102, 102, 102));
        pnlBarChartActive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBarChartActive.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                pnlBarChartActiveresizeCheck(evt);
            }
        });

        javax.swing.GroupLayout pnlBarChartActiveLayout = new javax.swing.GroupLayout(pnlBarChartActive);
        pnlBarChartActive.setLayout(pnlBarChartActiveLayout);
        pnlBarChartActiveLayout.setHorizontalGroup(
            pnlBarChartActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        pnlBarChartActiveLayout.setVerticalGroup(
            pnlBarChartActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlPieChart.setBackground(new java.awt.Color(102, 102, 102));
        pnlPieChart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlPieChartLayout = new javax.swing.GroupLayout(pnlPieChart);
        pnlPieChart.setLayout(pnlPieChartLayout);
        pnlPieChartLayout.setHorizontalGroup(
            pnlPieChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPieChartLayout.setVerticalGroup(
            pnlPieChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        pnlBarChartInActive.setBackground(new java.awt.Color(102, 102, 102));
        pnlBarChartInActive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlBarChartInActiveLayout = new javax.swing.GroupLayout(pnlBarChartInActive);
        pnlBarChartInActive.setLayout(pnlBarChartInActiveLayout);
        pnlBarChartInActiveLayout.setHorizontalGroup(
            pnlBarChartInActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        pnlBarChartInActiveLayout.setVerticalGroup(
            pnlBarChartInActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        pnlTextStats.setBackground(new java.awt.Color(0, 0, 0));
        pnlTextStats.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTextStats.setForeground(new java.awt.Color(255, 255, 255));

        pnlMealTypeStats.setBackground(new java.awt.Color(0, 0, 0));
        pnlMealTypeStats.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Meal Type Stats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlMealTypeStats.setForeground(new java.awt.Color(255, 255, 255));

        lblStandardMeal.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblStandardMeal.setForeground(new java.awt.Color(255, 255, 255));
        lblStandardMeal.setText("Standard");

        lblLowCarb.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblLowCarb.setForeground(new java.awt.Color(255, 255, 255));
        lblLowCarb.setText("Low Carb");

        lblKiddies.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblKiddies.setForeground(new java.awt.Color(255, 255, 255));
        lblKiddies.setText("Kiddies");

        jLabel28.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Meal Type");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel29.setText("Total");

        lblStandardTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblStandardTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblStandardTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStandardTotal.setText("0");

        lblLowCarbTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblLowCarbTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblLowCarbTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLowCarbTotal.setText("0");

        lblKiddiesTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblKiddiesTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblKiddiesTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblKiddiesTotal.setText("0");

        lblStandardMeal1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblStandardMeal1.setForeground(new java.awt.Color(255, 255, 255));
        lblStandardMeal1.setText("Standard");

        lblLowCarb1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblLowCarb1.setForeground(new java.awt.Color(255, 255, 255));
        lblLowCarb1.setText("Low Carb");

        lblKiddies1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblKiddies1.setForeground(new java.awt.Color(255, 255, 255));
        lblKiddies1.setText("Kiddies");

        lblStandardTotalInActive.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblStandardTotalInActive.setForeground(new java.awt.Color(255, 255, 255));
        lblStandardTotalInActive.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStandardTotalInActive.setText("0");

        lblLowCarbTotalInActive.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblLowCarbTotalInActive.setForeground(new java.awt.Color(255, 255, 255));
        lblLowCarbTotalInActive.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLowCarbTotalInActive.setText("0");

        lblKiddiesTotalinActive.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblKiddiesTotalinActive.setForeground(new java.awt.Color(255, 255, 255));
        lblKiddiesTotalinActive.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblKiddiesTotalinActive.setText("0");

        lblActive.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblActive.setForeground(new java.awt.Color(255, 255, 255));
        lblActive.setText("Active Meals:");

        lblInActive.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblInActive.setForeground(new java.awt.Color(255, 255, 255));
        lblInActive.setText("In-Active:");

        javax.swing.GroupLayout pnlMealTypeStatsLayout = new javax.swing.GroupLayout(pnlMealTypeStats);
        pnlMealTypeStats.setLayout(pnlMealTypeStatsLayout);
        pnlMealTypeStatsLayout.setHorizontalGroup(
            pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMealTypeStatsLayout.createSequentialGroup()
                .addComponent(jLabel28)
                .addGap(122, 122, 122)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMealTypeStatsLayout.createSequentialGroup()
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStandardMeal1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMealTypeStatsLayout.createSequentialGroup()
                        .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLowCarb1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKiddies1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(162, 162, 162)))
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMealTypeStatsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblStandardTotalInActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblLowCarbTotalInActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKiddiesTotalinActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnlMealTypeStatsLayout.createSequentialGroup()
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblKiddies)
                    .addComponent(lblLowCarb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStandardMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStandardTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLowCarbTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKiddiesTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnlMealTypeStatsLayout.createSequentialGroup()
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblActive)
                    .addComponent(lblInActive))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMealTypeStatsLayout.setVerticalGroup(
            pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMealTypeStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblActive)
                .addGap(10, 10, 10)
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStandardTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStandardMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLowCarbTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLowCarb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKiddiesTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKiddies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(lblInActive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStandardTotalInActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStandardMeal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLowCarb1)
                    .addComponent(lblLowCarbTotalInActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMealTypeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKiddies1)
                    .addComponent(lblKiddiesTotalinActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFamilySizeStats.setBackground(new java.awt.Color(0, 0, 0));
        pnlFamilySizeStats.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Family Size Stats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Family size");

        lblSingleFamilySize.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblSingleFamilySize.setForeground(new java.awt.Color(255, 255, 255));
        lblSingleFamilySize.setText("Single  (1)");

        lblCoupleFamilySize.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblCoupleFamilySize.setForeground(new java.awt.Color(255, 255, 255));
        lblCoupleFamilySize.setText("Couple  (2)");

        lblThreeFamilySize.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblThreeFamilySize.setForeground(new java.awt.Color(255, 255, 255));
        lblThreeFamilySize.setText("Three    (3)");

        lblFourFamilySize.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblFourFamilySize.setForeground(new java.awt.Color(255, 255, 255));
        lblFourFamilySize.setText("Four      (4)");

        lblFiveFamilySize.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblFiveFamilySize.setForeground(new java.awt.Color(255, 255, 255));
        lblFiveFamilySize.setText("Five       (5)");

        lblSixFamilySize.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblSixFamilySize.setForeground(new java.awt.Color(255, 255, 255));
        lblSixFamilySize.setText("Six         (6)");

        lblSingleFamilySizeTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblSingleFamilySizeTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSingleFamilySizeTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSingleFamilySizeTotal.setText("0");

        lblCoupleFamilySizeTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblCoupleFamilySizeTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblCoupleFamilySizeTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCoupleFamilySizeTotal.setText("0");

        lblThreeFamilySizeTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblThreeFamilySizeTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblThreeFamilySizeTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblThreeFamilySizeTotal.setText("0");

        lblFourFamilySizeTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblFourFamilySizeTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblFourFamilySizeTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFourFamilySizeTotal.setText("0");

        lblFiveFamilySizeTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblFiveFamilySizeTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblFiveFamilySizeTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFiveFamilySizeTotal.setText("0");

        lblSixFamilySizeTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblSixFamilySizeTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSixFamilySizeTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSixFamilySizeTotal.setText("0");

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Orders Of Family Size");

        lblMoreThanSixFamilySize.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblMoreThanSixFamilySize.setForeground(new java.awt.Color(255, 255, 255));
        lblMoreThanSixFamilySize.setText("More than Six");

        lblMoreThanSixFamilySizeTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblMoreThanSixFamilySizeTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblMoreThanSixFamilySizeTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMoreThanSixFamilySizeTotal.setText("0");

        javax.swing.GroupLayout pnlFamilySizeStatsLayout = new javax.swing.GroupLayout(pnlFamilySizeStats);
        pnlFamilySizeStats.setLayout(pnlFamilySizeStatsLayout);
        pnlFamilySizeStatsLayout.setHorizontalGroup(
            pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFamilySizeStatsLayout.createSequentialGroup()
                .addGroup(pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFamilySizeStatsLayout.createSequentialGroup()
                        .addComponent(lblSingleFamilySize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 221, Short.MAX_VALUE)
                        .addComponent(lblSingleFamilySizeTotal))
                    .addGroup(pnlFamilySizeStatsLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel40))
                    .addGroup(pnlFamilySizeStatsLayout.createSequentialGroup()
                        .addComponent(lblCoupleFamilySize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCoupleFamilySizeTotal))
                    .addGroup(pnlFamilySizeStatsLayout.createSequentialGroup()
                        .addComponent(lblThreeFamilySize)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblThreeFamilySizeTotal))
                    .addGroup(pnlFamilySizeStatsLayout.createSequentialGroup()
                        .addComponent(lblFourFamilySize)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblFourFamilySizeTotal))
                    .addGroup(pnlFamilySizeStatsLayout.createSequentialGroup()
                        .addComponent(lblFiveFamilySize)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblFiveFamilySizeTotal))
                    .addGroup(pnlFamilySizeStatsLayout.createSequentialGroup()
                        .addComponent(lblSixFamilySize)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSixFamilySizeTotal))
                    .addGroup(pnlFamilySizeStatsLayout.createSequentialGroup()
                        .addComponent(lblMoreThanSixFamilySize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMoreThanSixFamilySizeTotal)))
                .addContainerGap())
        );
        pnlFamilySizeStatsLayout.setVerticalGroup(
            pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFamilySizeStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSingleFamilySize)
                    .addComponent(lblSingleFamilySizeTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoupleFamilySize)
                    .addComponent(lblCoupleFamilySizeTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThreeFamilySize)
                    .addComponent(lblThreeFamilySizeTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFourFamilySize)
                    .addComponent(lblFourFamilySizeTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiveFamilySize)
                    .addComponent(lblFiveFamilySizeTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSixFamilySize)
                    .addComponent(lblSixFamilySizeTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFamilySizeStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoreThanSixFamilySize)
                    .addComponent(lblMoreThanSixFamilySizeTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTextStatsLayout = new javax.swing.GroupLayout(pnlTextStats);
        pnlTextStats.setLayout(pnlTextStatsLayout);
        pnlTextStatsLayout.setHorizontalGroup(
            pnlTextStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextStatsLayout.createSequentialGroup()
                .addComponent(pnlMealTypeStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlFamilySizeStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        pnlTextStatsLayout.setVerticalGroup(
            pnlTextStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTextStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFamilySizeStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMealTypeStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlMainChartBackgroundLayout = new javax.swing.GroupLayout(pnlMainChartBackground);
        pnlMainChartBackground.setLayout(pnlMainChartBackgroundLayout);
        pnlMainChartBackgroundLayout.setHorizontalGroup(
            pnlMainChartBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainChartBackgroundLayout.createSequentialGroup()
                .addGroup(pnlMainChartBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBarChartActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPieChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(pnlMainChartBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBarChartInActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTextStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlMainChartBackgroundLayout.setVerticalGroup(
            pnlMainChartBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainChartBackgroundLayout.createSequentialGroup()
                .addGroup(pnlMainChartBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBarChartInActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBarChartActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(pnlMainChartBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPieChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTextStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMainChartBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(pnlHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMainChartBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDriverTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverTblActionPerformed

    }//GEN-LAST:event_btnDriverTblActionPerformed

    private void btnDriverRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverRptActionPerformed
        DriverReport.getDriverData_Clientstb();
    }//GEN-LAST:event_btnDriverRptActionPerformed

    private void btnChefRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChefRptActionPerformed
        ChefReport.getChefData_Ordertb(); // get data relavant to ChefReport
    }//GEN-LAST:event_btnChefRptActionPerformed

    private void btnPackerRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackerRptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPackerRptActionPerformed

    private void btnHandlerRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHandlerRptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHandlerRptActionPerformed

    private void btnRouteViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRouteViewActionPerformed
        this.dispose();
        new DSC_RouteView().setVisible(true);
    }//GEN-LAST:event_btnRouteViewActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        this.dispose();
        new DSC_ViewOrder().setVisible(true);
    }//GEN-LAST:event_btnViewOrdersActionPerformed

    private void btnChangeChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeChartActionPerformed

        /*
                Removes All Componets from certain Panels.
         */
        pnlBarChartActive.removeAll();
        pnlBarChartInActive.removeAll();
        pnlBarChartActive.repaint();
        pnlBarChartInActive.repaint();
        checkGraph = false;


    }//GEN-LAST:event_btnChangeChartActionPerformed

    private void btnChangeStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStatisticsActionPerformed

    }//GEN-LAST:event_btnChangeStatisticsActionPerformed

    private void pnlBarChartActiveresizeCheck(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_pnlBarChartActiveresizeCheck

        /*
               Gets Executed When JFrame Resizes.
         */
        try {

            MainScreen_Charts.createBarGraph_ActiveAndInActiveMeals(pnlBarChartActive, pnlBarChartInActive, pnlPieChart, lblStandardTotal, lblLowCarbTotal, 
                                                                    lblKiddiesTotal, lblKiddiesTotalinActive, lblStandardTotalInActive, lblLowCarbTotalInActive,lblSingleFamilySizeTotal,
                                                                    lblCoupleFamilySizeTotal,lblThreeFamilySizeTotal,lblFourFamilySizeTotal,lblFiveFamilySizeTotal,
                                                                    lblSixFamilySizeTotal,lblMoreThanSixFamilySizeTotal, getData);
            getData = false;
            pnlBarChartActive.repaint();
            pnlBarChartInActive.repaint();
            pnlPieChart.repaint();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_pnlBarChartActiveresizeCheck

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        this.dispose();
        new DSC_Place_Order().setVisible(true);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSC_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSC_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSC_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSC_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSC_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeChart;
    private javax.swing.JButton btnChangeStatistics;
    private javax.swing.JButton btnChefRpt;
    private javax.swing.JButton btnDriverRpt;
    private javax.swing.JButton btnHandlerRpt;
    private javax.swing.JButton btnPackerRpt;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRouteView;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel lblActive;
    private javax.swing.JLabel lblCoupleFamilySize;
    private javax.swing.JLabel lblCoupleFamilySizeTotal;
    private javax.swing.JLabel lblFiveFamilySize;
    private javax.swing.JLabel lblFiveFamilySizeTotal;
    private javax.swing.JLabel lblFourFamilySize;
    private javax.swing.JLabel lblFourFamilySizeTotal;
    private javax.swing.JLabel lblGenerate;
    private javax.swing.JLabel lblInActive;
    private javax.swing.JLabel lblKiddies;
    private javax.swing.JLabel lblKiddies1;
    private javax.swing.JLabel lblKiddiesTotal;
    private javax.swing.JLabel lblKiddiesTotalinActive;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLowCarb;
    private javax.swing.JLabel lblLowCarb1;
    private javax.swing.JLabel lblLowCarbTotal;
    private javax.swing.JLabel lblLowCarbTotalInActive;
    private javax.swing.JLabel lblMoreThanSixFamilySize;
    private javax.swing.JLabel lblMoreThanSixFamilySizeTotal;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSingleFamilySize;
    private javax.swing.JLabel lblSingleFamilySizeTotal;
    private javax.swing.JLabel lblSixFamilySize;
    private javax.swing.JLabel lblSixFamilySizeTotal;
    private javax.swing.JLabel lblStandardMeal;
    private javax.swing.JLabel lblStandardMeal1;
    private javax.swing.JLabel lblStandardTotal;
    private javax.swing.JLabel lblStandardTotalInActive;
    private javax.swing.JLabel lblThreeFamilySize;
    private javax.swing.JLabel lblThreeFamilySizeTotal;
    private javax.swing.JLabel lblView;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBarChartActive;
    private javax.swing.JPanel pnlBarChartInActive;
    private javax.swing.JPanel pnlFamilySizeStats;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.JPanel pnlMainChartBackground;
    private javax.swing.JPanel pnlMealTypeStats;
    private javax.swing.JPanel pnlPieChart;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JPanel pnlTables;
    private javax.swing.JPanel pnlTextStats;
    // End of variables declaration//GEN-END:variables
}
